name = "travis-bourbon-collection"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "bourbon-collection"
database_id = "13b71248-8009-4c43-83c9-e9c6e3fa2e21"
